---
- name: backup nxos running config
  hosts: all
  gather_facts: false

  tasks:

    - name: Backup nxos config
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          dir_path: /tmp/home/network
          filename: "{{ inventory_hostname }}_backup.txt"
        
      register: backup
- name: copy backup to host   
  hosts: tower1.shadowman.dev
  gather_facts: false
  
  tasks:
    - name: save backup to controller
      ansible.builtin.copy:
        src: /tmp/home/network
        dest: "/home/rhusein/backups/"
    #  ansible_connection: local
    #  delegate_to: tower1.shadowman.dev