---
- name: backup nxos running config
  hosts: all
  gather_facts: false

  tasks:

    - name: Backup nxos config
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          dir_path: /tmp/
          filename: "{{ inventory_hostname }}_backup.txt"
        
      register: backup
    
    - name: save backup to controller
      ansible.builtin.copy:
        src: "{{ backup.backup_path }}"
        dest: "/home/rhusein/backups/"
        mode: "644"
      when: backup is defined
      ansible_connection: local
      delegate_to: tower1.shadowman.dev