---
- name: backup nxos running config
  hosts: switches
  gather_facts: false

  tasks:

    - name: Backup nxos config
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          dir_path: /tmp/home/network
          filename: "{{ inventory_hostname }}_backup.cfg"
        
      register: backup
      
- name: copy backup to host   
  hosts: report.shadowman.dev
  gather_facts: false
  
  tasks:
    - name: Create time stamp for play
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
      run_once: true

    - name: save backup to controller
      ansible.builtin.copy:
        src: /tmp/home/network
        dest: "/home/rhusein/backups/"
    #  ansible_connection: local
    #  delegate_to: tower1.shadowman.dev