---
- name: gather VLAN list
  hosts: leafs
  gather_facts: no

  tasks:

    - name: gather facts
      cisco.nxos.nxos_vlans:
        state: gathered
      register: result
    
    - name: print vlans
      debug:
        var: item['vlan_id']
      loop: "{{ result['gathered'] }}"
      failed_when: item['vlan_id'] is 2010



        
